#!/usr/bin/env python3
"""Build VERA's 8bpp PM5544 asset from its indexed 320x240 PNG.

The source SVG and its attribution are kept in ../assets. The PNG has already
been rasterized to 320x240 and mapped, without dithering, to the SVG's twenty
flat colours. This script emits the byte-for-byte VERA framebuffer and its
RGB444 palette as an Arduino PROGMEM header, plus a preview using the exact
colour precision VERA can display.
"""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
INPUT = ASSETS / "philips-pm5544-320x240-indexed.png"
HEADER = ROOT / "src" / "vera_driver" / "pm5544_image.h"
PREVIEW = ASSETS / "philips-pm5544-320x240-vera-rgb444.png"
CHUNK_SIZE = 25600


def rgb444(rgb: tuple[int, int, int]) -> tuple[int, int]:
    red, green, blue = (component >> 4 for component in rgb)
    return (green << 4) | blue, red


def main() -> None:
    image = Image.open(INPUT)
    if image.mode != "P" or image.size != (320, 240):
        raise SystemExit("expected a 320x240 indexed PNG")

    colors = image.getcolors(maxcolors=256)
    if colors is None:
        raise SystemExit("image exceeds VERA's 256-colour palette")
    used_indices = sorted(index for _, index in colors)
    palette = image.getpalette()

    rgb_palette = [tuple(palette[index * 3:index * 3 + 3])
                   for index in used_indices]
    pixels = image.tobytes()

    lines = [
        "// Generated by driver/tools/build_pm5544_asset.py. Do not edit.",
        "// Philips PM5544 derivative; see driver/assets/Philips_PM5544.LICENSE.md.",
        "#ifndef VERA_PM5544_IMAGE_H",
        "#define VERA_PM5544_IMAGE_H",
        "",
        "#include <avr/pgmspace.h>",
        "#include <stdint.h>",
        "",
        "#define PM5544_WIDTH 320u",
        "#define PM5544_HEIGHT 240u",
        "#define PM5544_IMAGE_BYTES 76800u",
        f"#define PM5544_PALETTE_ENTRIES {len(used_indices)}u",
        f"#define PM5544_IMAGE_CHUNK_BYTES {CHUNK_SIZE}u",
        "",
        "static const uint8_t pm5544_palette[][2] PROGMEM = {",
    ]
    for rgb in rgb_palette:
        low, high = rgb444(rgb)
        lines.append(f"  {{0x{low:02X}, 0x{high:02X}}},")
    lines.extend(["};", ""])
    chunks = [pixels[offset:offset + CHUNK_SIZE]
              for offset in range(0, len(pixels), CHUNK_SIZE)]
    for number, chunk in enumerate(chunks):
        lines.append(f"static const uint8_t pm5544_pixels_{number}[] PROGMEM = {{")
        for offset in range(0, len(chunk), 16):
            values = ", ".join(f"0x{value:02X}" for value in chunk[offset:offset + 16])
            lines.append(f"  {values},")
        lines.extend(["};", ""])
    lines.extend([
        "static uint8_t pm5544_pixel_at(uint32_t offset) {",
        "  if (offset < PM5544_IMAGE_CHUNK_BYTES) {",
        "    return pgm_read_byte_far(pgm_get_far_address(pm5544_pixels_0) + offset);",
        "  }",
        "  if (offset < 2UL * PM5544_IMAGE_CHUNK_BYTES) {",
        "    return pgm_read_byte_far(pgm_get_far_address(pm5544_pixels_1) +",
        "                             offset - PM5544_IMAGE_CHUNK_BYTES);",
        "  }",
        "  return pgm_read_byte_far(pgm_get_far_address(pm5544_pixels_2) +",
        "                           offset - 2UL * PM5544_IMAGE_CHUNK_BYTES);",
        "}",
        "",
        "#endif  // VERA_PM5544_IMAGE_H",
        "",
    ])
    HEADER.write_text("\n".join(lines), encoding="ascii")

    preview_palette = []
    for rgb in rgb_palette:
        low, high = rgb444(rgb)
        preview_palette.extend([
            ((high & 0x0F) * 17), ((low >> 4) * 17), ((low & 0x0F) * 17)
        ])
    preview_palette.extend([0] * (768 - len(preview_palette)))
    preview = Image.frombytes("P", image.size, pixels)
    preview.putpalette(preview_palette)
    preview.save(PREVIEW)


if __name__ == "__main__":
    main()
